version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Chicago
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - dependencies
