name: Pull Request Build

on:
  pull_request:
    branches:
      - master

jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          # A directory to store and save the cache
          path: ~/.m2
          key: m2
      - name: Run Unit Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report --file test_pom.xml
      - name: Publish Unit Test Results Report
        uses: scacap/action-surefire-report@v1
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
      - name: Upload Test Result Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Logs
          path: ./**/logs
